### ISSUE TITLE
Is it possible to write gpx file dynamically?

### ISSUE THREAD

**Issue by sun-jiao** [jenetics/jpx#124]
Is it possible to write gpx file dynamically, write every geopoint one-by-one, rather than write the whole gpx object after finishing the geo-tracking like your example?

**Comment by jenetics** [comment]
I'm sorry, but it is not possible to write a GPX file one-by-one. The reason for this is, that the GPX format is written as XML, which doesn't support appending elements. If you want to persist the way-points while logging, you have to do this in an _appendable_ form, like CSV. After finishing logging you can create a valid GPX file from the logged way-points.

Instead of CSV you can use the `WayPoint` Java serialization directly and append it to an `ObjectOutputStream`. How to do this is described here: https://stackoverflow.com/questions/1194656/appending-to-an-objectoutputstream

I also tried this solution in a Gist: https://gist.github.com/jenetics/279c6c620b45c8eb0c540acbee4aea71

**Comment by sun-jiao** [comment]
> I'm sorry, but it is not possible to write a GPX file one-by-one. The reason for this is, that the GPX format is written as XML, which doesn't support appending elements. If you want to persist the way-points while logging, you have to do this in an _appendable_ form, like CSV. After finishing logging you can create a valid GPX file from the logged way-points.
> 
> Instead of CSV you can use the `WayPoint` Java serialization directly and append it to an `ObjectOutputStream`. How to do this is described here: https://stackoverflow.com/questions/1194656/appending-to-an-objectoutputstream
> 
> I also tried this solution in a Gist: https://gist.github.com/jenetics/279c6c620b45c8eb0c540acbee4aea71

Thanks so much, I'll try it.
