### ISSUE TITLE
Define stable module name

### ISSUE THREAD

**Issue by jenetics** [jenetics/jpx#26]
As a preparation step for Java 9 and JPMS (Jigsaw), all Jenetics modules should define a stable module name in the `MANIFEST.MF` file by adding a `Automatic-Module-Name` entry.

```
Automatic-Module-Name: io.jenetics.jpx
```

*See:*
* [Java SE 9 - JPMS automatic modules](http://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html)

**Comment by jenetics** [comment]
Version 1.1.1 released.

**Comment by Adito5393** [comment]
Hey, I've just forked your project and I will attempt to write the module-info.java file because that is the proper way to move forward from Java 9 onwards. Once I'm done and test it, I will make the pull request for you to review.

Let me know if you already tried and failed and the details such that I can have a heads start on possible upcoming problems.

PS: Good job on the project and thanks for making it open source!!
