### ISSUE TITLE
android support

### ISSUE THREAD

**Issue by zebrah** [jenetics/jpx#76]
The library looks really nice but I haven't been able to use it with Android Studio 3.2.1. During testing libraries missing from the android jdk implementation seem to lead to runtime errors. Is there any work been done to remedy android support at this time?

**Comment by jenetics** [comment]
Is this problem similar to #65 ?

**Comment by zebrah** [comment]
Possibly. I've written a barebones test that involves calling GPX.read() on a test gpx file and I get the following error: 

```
 java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/stream/XMLInputFactory;
        at io.jenetics.jpx.GPX$Reader.read(GPX.java:1061)
        at io.jenetics.jpx.GPX.read(GPX.java:1820)
```

**Comment by jenetics** [comment]
And you tried to add https://mvnrepository.com/artifact/stax/stax-api/1.0.1 to the classpath?

**Comment by jenetics** [comment]
Seems that some additional dependencies are missing. Since I have no experience with Android development, I can't give you any advice. Maybe you can post the needed setup if you find a solution.

**Comment by zebrah** [comment]
I think I got it. The following dependencies seem to be the right recipe: 

```
   implementation 'io.jenetics:jpx:1.4.0'
   implementation 'stax:stax-api:1.0.1'
   implementation 'com.fasterxml:aalto-xml:1.1.1'
```

We can close it now :) Thanks for your help.

**Comment by tonsV2** [comment]
I had to use the following

    implementation 'io.jenetics:jpx:2.0.0'
    implementation 'stax:stax:1.2.0'

And add the following proguard rules

    -keep class javax.xml.stream.** { *; }
    -keep class com.bea.xml.stream.** { *; }

**Comment by mipastgt** [comment]
Just an update for those coming here after a google search like me because they have a problem.

I got JPX working on Android with the following combination of libraries:

```
    implementation("io.jenetics:jpx:2.2.0")
    implementation("com.fasterxml:aalto-xml:1.3.0")
```

The proposal by @tonsV2 did not work for me. His versions seem to have some incompatibilities.

The proposal by @ghost (whoever that was) is a bit outdated now but did still work but the explicit dependency on stax-api does not seem to be necessary at all. With the updated dependencies JPX seems to work nicely on Android.
